server:
  port: 8080

logging:
  level:
    root: INFO
    com.tenco.spring_blog: INFO


spring:
  # 데이터 베이스 연결 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # H2  콘솔 화면 켜기 (http://localhost:8080/h2-console)
    h2:
      console:
        enabled: true

  # JPA 설정
  jpa:
    hibernate:
      default_batch_fetch_size: 10
      # 운영에서는 create 를 쓰지 않습니다. 없는 테이블과 컬럼만 추가합니다
      ddl-auto: update
    # 실행되는 SQL을 콘솔에 출력합니다
    show-sql: true
    properties:
      hibernate:
        format_sql: true     # 출력되는 SQL을 콘솔창에 줄바꿈해 보기 좋게 표시
    # 추후 data.sql 을 테이블 생성후에 실행합니다
    defer-datasource-initialization: true

  # 서버 시작시 이 파일 실행
  sql:
    init:
      data-locations:
        - classpath:db/data.sql