spring:
  config:
    import: optional:file:.env[.properties]  #스프링 .env 를 자동으로 읽지 않습니다 읽을 수 있도록 설정 추가
  mustache:
    servlet:
      expose-session-attributes: true # 머스태치 파일에서 세션 담을 값ㅇ르 바로 사용 가능
  profiles:
    active: local